#!/usr/bin/env node
// Regenerates supabase/setup.sql — the documented "paste this one file into the Supabase SQL
// editor" installer — from the files that are actually applied to the database:
//
//   supabase/schema.sql            base schema, with its generic demo seed swapped out for
//                                  supabase/seed.sql (the venue's real configuration)
//   supabase/migrations/*.sql      every migration, in filename order
//
// Run with: npm run build:schema      (add --check to fail instead of writing, for CI)
//
// WHY THE SEED IS SWAPPED
// schema.sql is history: it is the file that was already run against the live database, and it
// carries the generic demo seed it shipped with. setup.sql must instead install Invictus's real
// six bays, 24/7 hours and $20/$25 rates. A later migration cannot fix that, because the seed is
// "on conflict (id) do nothing" — the first insert wins, so the generic one would always win.
// So the substitution happens here, and it is fail-loud: if the generic seed statement can no
// longer be located in schema.sql, this script exits non-zero rather than quietly shipping an
// installer that configures the wrong venue.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'supabase');
const outPath = join(dir, 'setup.sql');

const die = (msg) => { console.error(`build:schema — ${msg}`); process.exit(1); };

// --- the base schema, with the real seed substituted in ---------------------------------

// The seed statement in schema.sql runs from its "-- Seed …" comment through the
// "on conflict (id) do nothing;" that terminates the insert. Both markers must appear
// exactly once, or the file has changed shape and a human needs to look at it.
function realSeedSchema() {
  const lines = readFileSync(join(dir, 'schema.sql'), 'utf8').split('\n');
  const starts = lines.reduce((a, l, i) => (l.startsWith('-- Seed ') ? [...a, i] : a), []);
  const ends = lines.reduce((a, l, i) => (l === 'on conflict (id) do nothing;' ? [...a, i] : a), []);
  if (starts.length !== 1 || ends.length !== 1 || starts[0] > ends[0]) {
    die('could not locate exactly one settings seed in supabase/schema.sql ' +
        `(found ${starts.length} "-- Seed …" comments, ${ends.length} "on conflict (id) do nothing;"). ` +
        'setup.sql was NOT written — fix the markers or update scripts/build-schema.mjs.');
  }
  const seed = readFileSync(join(dir, 'seed.sql'), 'utf8').trimEnd().split('\n');
  return [...lines.slice(0, starts[0]), ...seed, ...lines.slice(ends[0] + 1)].join('\n').trimEnd() + '\n';
}

// --- section assembly -------------------------------------------------------------------

const rule = (n) => '-- ' + '='.repeat(n);
const section = (title, body) => `${rule(74)}\n-- ${title}\n${rule(74)}\n\n${body.trimEnd()}\n`;

// 0007_override_blocks.sql -> "MIGRATION 0007 - OVERRIDE BLOCKS"
const titleOf = (file) => {
  const m = /^(\d{4})_(.+)\.sql$/.exec(file);
  if (!m) die(`migration filename "${file}" is not NNNN_some_name.sql`);
  return `MIGRATION ${m[1]} - ${m[2].replace(/_/g, ' ').toUpperCase()}`;
};

const migrations = readdirSync(join(dir, 'migrations')).filter((f) => f.endsWith('.sql')).sort();
if (!migrations.length) die('supabase/migrations/ contains no .sql files');

const header = `${rule(77)}
-- Invictus Golf - complete database setup, in one file.
--
-- HOW TO RUN
--   Supabase -> SQL Editor -> New query -> paste this whole file -> Run.
--
-- This is the base schema plus all ${migrations.length} migrations, in the order they were
-- written, followed by nothing else you need to run separately.
--
-- SAFE TO RE-RUN, AND SAFE ON A DATABASE THAT ALREADY HAS YOUR DATA. Every
-- statement uses "if not exists", "add column if not exists" or "drop policy if
-- exists", and every seed uses "on conflict do nothing" - so a second run adds
-- only what is missing. It never overwrites your settings, bays, prices,
-- bookings, customers or staff, and never deletes anything.
--
-- Two things worth knowing before you run it on a live database:
--   * Customers' own logins are never turned into staff logins. Only accounts
--     that are already staff keep portal access.
--   * It re-asserts every security policy, so anything changed by hand in the
--     Supabase dashboard goes back to what this file says.
--
-- AFTER RUNNING, create the manager login:
--   Supabase -> Authentication -> Users -> Add user (email + password).
--   Every table below grants write access to "authenticated" only.
--
-- GENERATED by "npm run build:schema" from schema.sql + seed.sql + migrations/.
-- Do not edit this file by hand; edit those and re-run the script.
${rule(77)}
`;

const parts = [
  header,
  section('BASE SCHEMA - settings, bookings, row level security', realSeedSchema()),
  ...migrations.map((f) => section(titleOf(f), readFileSync(join(dir, 'migrations', f), 'utf8'))),
];
const out = parts.join('\n\n');

if (process.argv.includes('--check')) {
  const current = readFileSync(outPath, 'utf8');
  if (current !== out) die('supabase/setup.sql is out of date. Run "npm run build:schema".');
  console.log(`build:schema — setup.sql is up to date (base schema + ${migrations.length} migrations).`);
} else {
  writeFileSync(outPath, out);
  console.log(`build:schema — wrote supabase/setup.sql (base schema + ${migrations.length} migrations, ${out.split('\n').length - 1} lines).`);
}
